# syntax=docker/dockerfile:1
FROM ubuntu
RUN apt update
# DataLab
RUN apt install -y cmake vim 
RUN apt install -y gcc-multilib
RUN apt install -y gdb

RUN apt update

RUN apt install -y build-essential g++-multilib

RUN apt update
